[Host]
Incremental=yes

[Build]
CacheDirectory=../../pmos-cache
KeepBuildDirectory=yes

[Output]
Format=directory
CacheDirectory=../../pmos-cache

[Content]
BaseTrees=../../pmos-rootfs
Incremental=yes
